baseURL = "http://mynameisbart.com/"
languageCode = "en-us"
title = "My name is Bart"
description = ""
theme = "terminal"
sectionPagesMenu = "main"

# Syntax highlighting.
pygmentsOptions = "linenos=true"
pygmentsCodeFences = true
pygmentsUseClasses = true

[author]
    name = "Bart Feenstra"
